### ISSUE TITLE
[INIT] 프로젝트 세팅 

### ISSUE THREAD

**Issue by youngeun-dev** [portfolio-diary/Back-end#1]
## 💡 Issue
프로젝트를 생성 후 개발을 위한 설정을 추가합니다.

## 📝  todo
- [x] SpringBoot 프로젝트 생성
- [x] docker compose로 mariadb 사용
- [x] querydsl 설정
- [x] base response & error response 추가
- [x] member, post, file, experience, tag 도메인 추가 
  - [x] controller, service, repository, entity
